name: Der Hinterhof
favicon: null
layout_spectrum: 0.25478
typography_spectrum: 0.99795
title: Der Hinterhof
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7f5f8'
    - '#97d9f1'
    - '#183e55'
    - '#7fb8c9'
    - '#3a7088'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
